language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
#    - "pypy3"

install:
    - pip install .

script: python -m unittest discover -s tests

branches:
    only:
        - master
        - dev
